plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'id.manjo.gopaybridge'
version = '1.0.0'

android {
  namespace 'expo.modules.gopaylistener'

  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }

  testOptions {
    unitTests.includeAndroidResources = true
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}
